# Autogenerated. Do not modify.
#
# Profile: 21.212.0
from typing import Optional

from fit_tool.base_type import BaseType
from fit_tool.data_message import DataMessage
from fit_tool.definition_message import DefinitionMessage
from fit_tool.developer_field import DeveloperField
from fit_tool.endian import Endian
from fit_tool.field import Field
from fit_tool.sub_field import SubField
from fit_tool.profile.messages.common_fields import MessageIndexField, TimestampField
from fit_tool.profile.profile_type import *
from typing import List as list
from typing import Dict as dict


class WeightScaleMessage(DataMessage):
    """WeightScaleMessage — use blank construct for authoring, ``from_definition`` for decode.

    * ``WeightScaleMessage()`` — create path: growable fields, no wire definition.
    * ``WeightScaleMessage.from_definition(definition, developer_fields=...)`` —
      project a local definition onto this type (decode / MessageFactory path).
    """

    ID = 30
    NAME = 'weight_scale'

    @staticmethod
    def _field_size_from_definition(definition_message: DefinitionMessage, field_id: int) -> int:
        field_definition = definition_message.get_field_definition(field_id)
        if field_definition:
            return field_definition.size
        return 0

    def __init__(self, developer_fields=None, local_id: int = 0,
                 endian: Endian = Endian.LITTLE):
        """Create a blank message for authoring (growable fields, no definition)."""
        super().__init__(name=WeightScaleMessage.NAME,
                         global_id=WeightScaleMessage.ID,
                         local_id=local_id,
                         endian=endian,
                         definition_message=None,
                         developer_fields=developer_fields,
                         fields=[
        TimestampField(
            size=0,
            growable=True), 
        WeightScaleWeightField(
            size=0,
            growable=True), 
        WeightScalePercentFatField(
            size=0,
            growable=True), 
        WeightScalePercentHydrationField(
            size=0,
            growable=True), 
        WeightScaleVisceralFatMassField(
            size=0,
            growable=True), 
        WeightScaleBoneMassField(
            size=0,
            growable=True), 
        WeightScaleMuscleMassField(
            size=0,
            growable=True), 
        WeightScaleBasalMetField(
            size=0,
            growable=True), 
        WeightScalePhysiqueRatingField(
            size=0,
            growable=True), 
        WeightScaleActiveMetField(
            size=0,
            growable=True), 
        WeightScaleMetabolicAgeField(
            size=0,
            growable=True), 
        WeightScaleVisceralFatRatingField(
            size=0,
            growable=True), 
        WeightScaleUserProfileIndexField(
            size=0,
            growable=True), 
        WeightScaleBmiField(
            size=0,
            growable=True)
        ])

        self.growable = True

    @classmethod
    def from_definition(cls, definition_message: DefinitionMessage,
                        developer_fields: list[DeveloperField] = None):
        """Project a wire definition onto this message type (decode path).

        Field sizes come from the definition; fields are not growable. Prefer this
        over passing a definition into ``__init__``.
        """
        message = cls.__new__(cls)
        DataMessage.__init__(
            message,
            name=cls.NAME,
            global_id=cls.ID,
            local_id=definition_message.local_id,
            endian=definition_message.endian,
            definition_message=definition_message,
            developer_fields=developer_fields,
            fields=[
        TimestampField(
            size=cls._field_size_from_definition(
                definition_message, TimestampField.ID),
            growable=False), 
        WeightScaleWeightField(
            size=cls._field_size_from_definition(
                definition_message, WeightScaleWeightField.ID),
            growable=False), 
        WeightScalePercentFatField(
            size=cls._field_size_from_definition(
                definition_message, WeightScalePercentFatField.ID),
            growable=False), 
        WeightScalePercentHydrationField(
            size=cls._field_size_from_definition(
                definition_message, WeightScalePercentHydrationField.ID),
            growable=False), 
        WeightScaleVisceralFatMassField(
            size=cls._field_size_from_definition(
                definition_message, WeightScaleVisceralFatMassField.ID),
            growable=False), 
        WeightScaleBoneMassField(
            size=cls._field_size_from_definition(
                definition_message, WeightScaleBoneMassField.ID),
            growable=False), 
        WeightScaleMuscleMassField(
            size=cls._field_size_from_definition(
                definition_message, WeightScaleMuscleMassField.ID),
            growable=False), 
        WeightScaleBasalMetField(
            size=cls._field_size_from_definition(
                definition_message, WeightScaleBasalMetField.ID),
            growable=False), 
        WeightScalePhysiqueRatingField(
            size=cls._field_size_from_definition(
                definition_message, WeightScalePhysiqueRatingField.ID),
            growable=False), 
        WeightScaleActiveMetField(
            size=cls._field_size_from_definition(
                definition_message, WeightScaleActiveMetField.ID),
            growable=False), 
        WeightScaleMetabolicAgeField(
            size=cls._field_size_from_definition(
                definition_message, WeightScaleMetabolicAgeField.ID),
            growable=False), 
        WeightScaleVisceralFatRatingField(
            size=cls._field_size_from_definition(
                definition_message, WeightScaleVisceralFatRatingField.ID),
            growable=False), 
        WeightScaleUserProfileIndexField(
            size=cls._field_size_from_definition(
                definition_message, WeightScaleUserProfileIndexField.ID),
            growable=False), 
        WeightScaleBmiField(
            size=cls._field_size_from_definition(
                definition_message, WeightScaleBmiField.ID),
            growable=False)
        ])
        message.growable = False
        # Keep definition field ids not present in the Profile schema (Stage 2 E).
        message.retain_unknown_fields()
        return message

    @classmethod
    def from_bytes(cls, definition_message: DefinitionMessage, developer_fields: list[DeveloperField],
                   bytes_buffer: bytes, offset: int = 0):
        message = cls.from_definition(definition_message, developer_fields=developer_fields)
        message.read_from_bytes(bytes_buffer, offset)
        return message



# timestamp : milliseconds from January 1st, 1970 at 00:00:00 UTC

    @property
    def timestamp(self) -> Optional[int]:
        field = self.get_field(TimestampField.ID)
        if field and field.is_valid():
            sub_field = field.get_valid_sub_field(self.fields)
            return field.get_value(sub_field=sub_field)
        else:
            return None


    # timestamp : milliseconds from January 1st, 1970 at 00:00:00 UTC

    @timestamp.setter
    def timestamp(self, value: int):
        field = self.get_field(TimestampField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                sub_field = field.get_valid_sub_field(self.fields)
                field.set_value(0, value, sub_field)

    

    @property
    def weight(self) -> Optional[float]:
        field = self.get_field(WeightScaleWeightField.ID)
        if field and field.is_valid():
            sub_field = field.get_valid_sub_field(self.fields)
            return field.get_value(sub_field=sub_field)
        else:
            return None



    @weight.setter
    def weight(self, value: float):
        field = self.get_field(WeightScaleWeightField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                sub_field = field.get_valid_sub_field(self.fields)
                field.set_value(0, value, sub_field)

    

    @property
    def percent_fat(self) -> Optional[float]:
        field = self.get_field(WeightScalePercentFatField.ID)
        if field and field.is_valid():
            sub_field = field.get_valid_sub_field(self.fields)
            return field.get_value(sub_field=sub_field)
        else:
            return None



    @percent_fat.setter
    def percent_fat(self, value: float):
        field = self.get_field(WeightScalePercentFatField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                sub_field = field.get_valid_sub_field(self.fields)
                field.set_value(0, value, sub_field)

    

    @property
    def percent_hydration(self) -> Optional[float]:
        field = self.get_field(WeightScalePercentHydrationField.ID)
        if field and field.is_valid():
            sub_field = field.get_valid_sub_field(self.fields)
            return field.get_value(sub_field=sub_field)
        else:
            return None



    @percent_hydration.setter
    def percent_hydration(self, value: float):
        field = self.get_field(WeightScalePercentHydrationField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                sub_field = field.get_valid_sub_field(self.fields)
                field.set_value(0, value, sub_field)

    

    @property
    def visceral_fat_mass(self) -> Optional[float]:
        field = self.get_field(WeightScaleVisceralFatMassField.ID)
        if field and field.is_valid():
            sub_field = field.get_valid_sub_field(self.fields)
            return field.get_value(sub_field=sub_field)
        else:
            return None



    @visceral_fat_mass.setter
    def visceral_fat_mass(self, value: float):
        field = self.get_field(WeightScaleVisceralFatMassField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                sub_field = field.get_valid_sub_field(self.fields)
                field.set_value(0, value, sub_field)

    

    @property
    def bone_mass(self) -> Optional[float]:
        field = self.get_field(WeightScaleBoneMassField.ID)
        if field and field.is_valid():
            sub_field = field.get_valid_sub_field(self.fields)
            return field.get_value(sub_field=sub_field)
        else:
            return None



    @bone_mass.setter
    def bone_mass(self, value: float):
        field = self.get_field(WeightScaleBoneMassField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                sub_field = field.get_valid_sub_field(self.fields)
                field.set_value(0, value, sub_field)

    

    @property
    def muscle_mass(self) -> Optional[float]:
        field = self.get_field(WeightScaleMuscleMassField.ID)
        if field and field.is_valid():
            sub_field = field.get_valid_sub_field(self.fields)
            return field.get_value(sub_field=sub_field)
        else:
            return None



    @muscle_mass.setter
    def muscle_mass(self, value: float):
        field = self.get_field(WeightScaleMuscleMassField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                sub_field = field.get_valid_sub_field(self.fields)
                field.set_value(0, value, sub_field)

    

    @property
    def basal_met(self) -> Optional[float]:
        field = self.get_field(WeightScaleBasalMetField.ID)
        if field and field.is_valid():
            sub_field = field.get_valid_sub_field(self.fields)
            return field.get_value(sub_field=sub_field)
        else:
            return None



    @basal_met.setter
    def basal_met(self, value: float):
        field = self.get_field(WeightScaleBasalMetField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                sub_field = field.get_valid_sub_field(self.fields)
                field.set_value(0, value, sub_field)

    

    @property
    def physique_rating(self) -> Optional[int]:
        field = self.get_field(WeightScalePhysiqueRatingField.ID)
        if field and field.is_valid():
            sub_field = field.get_valid_sub_field(self.fields)
            return field.get_value(sub_field=sub_field)
        else:
            return None



    @physique_rating.setter
    def physique_rating(self, value: int):
        field = self.get_field(WeightScalePhysiqueRatingField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                sub_field = field.get_valid_sub_field(self.fields)
                field.set_value(0, value, sub_field)

    

    @property
    def active_met(self) -> Optional[float]:
        field = self.get_field(WeightScaleActiveMetField.ID)
        if field and field.is_valid():
            sub_field = field.get_valid_sub_field(self.fields)
            return field.get_value(sub_field=sub_field)
        else:
            return None



    @active_met.setter
    def active_met(self, value: float):
        field = self.get_field(WeightScaleActiveMetField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                sub_field = field.get_valid_sub_field(self.fields)
                field.set_value(0, value, sub_field)

    

    @property
    def metabolic_age(self) -> Optional[int]:
        field = self.get_field(WeightScaleMetabolicAgeField.ID)
        if field and field.is_valid():
            sub_field = field.get_valid_sub_field(self.fields)
            return field.get_value(sub_field=sub_field)
        else:
            return None



    @metabolic_age.setter
    def metabolic_age(self, value: int):
        field = self.get_field(WeightScaleMetabolicAgeField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                sub_field = field.get_valid_sub_field(self.fields)
                field.set_value(0, value, sub_field)

    

    @property
    def visceral_fat_rating(self) -> Optional[int]:
        field = self.get_field(WeightScaleVisceralFatRatingField.ID)
        if field and field.is_valid():
            sub_field = field.get_valid_sub_field(self.fields)
            return field.get_value(sub_field=sub_field)
        else:
            return None



    @visceral_fat_rating.setter
    def visceral_fat_rating(self, value: int):
        field = self.get_field(WeightScaleVisceralFatRatingField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                sub_field = field.get_valid_sub_field(self.fields)
                field.set_value(0, value, sub_field)

    

    @property
    def user_profile_index(self) -> Optional[int]:
        field = self.get_field(WeightScaleUserProfileIndexField.ID)
        if field and field.is_valid():
            sub_field = field.get_valid_sub_field(self.fields)
            return field.get_value(sub_field=sub_field)
        else:
            return None



    @user_profile_index.setter
    def user_profile_index(self, value: int):
        field = self.get_field(WeightScaleUserProfileIndexField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                sub_field = field.get_valid_sub_field(self.fields)
                field.set_value(0, value, sub_field)

    

    @property
    def bmi(self) -> Optional[float]:
        field = self.get_field(WeightScaleBmiField.ID)
        if field and field.is_valid():
            sub_field = field.get_valid_sub_field(self.fields)
            return field.get_value(sub_field=sub_field)
        else:
            return None



    @bmi.setter
    def bmi(self, value: float):
        field = self.get_field(WeightScaleBmiField.ID)

        if field:
            if value is None:
                field.clear()
            else:
                sub_field = field.get_valid_sub_field(self.fields)
                field.set_value(0, value, sub_field)

    





class WeightScaleWeightField(Field):
    ID = 0

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='weight',
            field_id=self.ID,
            base_type=BaseType.UINT16,
        offset = 0,
                 scale = 100,
                         size = size,
        units = 'kg',
        type_name = 'weight',
        growable = growable,
                   sub_fields = [
        ]
        )


class WeightScalePercentFatField(Field):
    ID = 1

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='percent_fat',
            field_id=self.ID,
            base_type=BaseType.UINT16,
        offset = 0,
                 scale = 100,
                         size = size,
        units = '%',
        type_name = 'uint16',
        growable = growable,
                   sub_fields = [
        ]
        )


class WeightScalePercentHydrationField(Field):
    ID = 2

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='percent_hydration',
            field_id=self.ID,
            base_type=BaseType.UINT16,
        offset = 0,
                 scale = 100,
                         size = size,
        units = '%',
        type_name = 'uint16',
        growable = growable,
                   sub_fields = [
        ]
        )


class WeightScaleVisceralFatMassField(Field):
    ID = 3

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='visceral_fat_mass',
            field_id=self.ID,
            base_type=BaseType.UINT16,
        offset = 0,
                 scale = 100,
                         size = size,
        units = 'kg',
        type_name = 'uint16',
        growable = growable,
                   sub_fields = [
        ]
        )


class WeightScaleBoneMassField(Field):
    ID = 4

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='bone_mass',
            field_id=self.ID,
            base_type=BaseType.UINT16,
        offset = 0,
                 scale = 100,
                         size = size,
        units = 'kg',
        type_name = 'uint16',
        growable = growable,
                   sub_fields = [
        ]
        )


class WeightScaleMuscleMassField(Field):
    ID = 5

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='muscle_mass',
            field_id=self.ID,
            base_type=BaseType.UINT16,
        offset = 0,
                 scale = 100,
                         size = size,
        units = 'kg',
        type_name = 'uint16',
        growable = growable,
                   sub_fields = [
        ]
        )


class WeightScaleBasalMetField(Field):
    ID = 7

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='basal_met',
            field_id=self.ID,
            base_type=BaseType.UINT16,
        offset = 0,
                 scale = 4,
                         size = size,
        units = 'kcal/day',
        type_name = 'uint16',
        growable = growable,
                   sub_fields = [
        ]
        )


class WeightScalePhysiqueRatingField(Field):
    ID = 8

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='physique_rating',
            field_id=self.ID,
            base_type=BaseType.UINT8,
        offset = 0,
                 scale = 1,
                         size = size,
        type_name = 'uint8',
        growable = growable,
                   sub_fields = [
        ]
        )


class WeightScaleActiveMetField(Field):
    ID = 9

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='active_met',
            field_id=self.ID,
            base_type=BaseType.UINT16,
        offset = 0,
                 scale = 4,
                         size = size,
        units = 'kcal/day',
        type_name = 'uint16',
        growable = growable,
                   sub_fields = [
        ]
        )


class WeightScaleMetabolicAgeField(Field):
    ID = 10

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='metabolic_age',
            field_id=self.ID,
            base_type=BaseType.UINT8,
        offset = 0,
                 scale = 1,
                         size = size,
        units = 'years',
        type_name = 'uint8',
        growable = growable,
                   sub_fields = [
        ]
        )


class WeightScaleVisceralFatRatingField(Field):
    ID = 11

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='visceral_fat_rating',
            field_id=self.ID,
            base_type=BaseType.UINT8,
        offset = 0,
                 scale = 1,
                         size = size,
        type_name = 'uint8',
        growable = growable,
                   sub_fields = [
        ]
        )


class WeightScaleUserProfileIndexField(Field):
    ID = 12

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='user_profile_index',
            field_id=self.ID,
            base_type=BaseType.UINT16,
        offset = 0,
                 scale = 1,
                         size = size,
        type_name = 'message_index',
        growable = growable,
                   sub_fields = [
        ]
        )


class WeightScaleBmiField(Field):
    ID = 13

    def __init__(self, size: int = 0, growable: bool = True):
        super().__init__(
            name='bmi',
            field_id=self.ID,
            base_type=BaseType.UINT16,
        offset = 0,
                 scale = 10,
                         size = size,
        units = 'kg/m^2',
        type_name = 'uint16',
        growable = growable,
                   sub_fields = [
        ]
        )